export const REFRESH_USERS_LIST = 'REFRESH_USERS_LIST';
export const REFRESH_USER_CARD = 'REFRESH_USER_CARD';
export const THROW_ERROR_MESSAGE = 'THROW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';


