export const REFRESH_USERS_LIST = 'REFRESH_USERS_LIST';
export const REFRESH_AND_SHOW_USER_CARD = 'REFRESH_AND_SHOW_USER_CARD';
export const HIDE_USER_CARD = 'HIDE_USER_CARD';
export const THROW_ERROR_MESSAGE = 'THROW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';


