const InitialState = {
  usersList: [{
    avatar_url: "https://avatars1.githubusercontent.com/u/11541426?v=4",
    events_url: "https://api.github.com/users/blynkkk/events{/privacy}",
    followers_url: "https://api.github.com/users/blynkkk/followers",
    following_url: "https://api.github.com/users/blynkkk/following{/other_user}",
    gists_url: "https://api.github.com/users/blynkkk/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/blynkkk",
    id: 11541426,
    login: "blynkkk",
    node_id: "MDQ6VXNlcjExNTQxNDI2",
    organizations_url: "https://api.github.com/users/blynkkk/orgs",
    received_events_url: "https://api.github.com/users/blynkkk/received_events",
    repos_url: "https://api.github.com/users/blynkkk/repos",
    score: 1,
    site_admin: false,
    starred_url: "https://api.github.com/users/blynkkk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/blynkkk/subscriptions",
    type: "User",
    url: "https://api.github.com/users/blynkkk",
  },
    {
      avatar_url: "https://avatars2.githubusercontent.com/u/4405297?v=4",
      events_url: "https://api.github.com/users/tshemsedinov/events{/privacy}",
      followers_url: "https://api.github.com/users/tshemsedinov/followers",
      following_url: "https://api.github.com/users/tshemsedinov/following{/other_user}",
      gists_url: "https://api.github.com/users/tshemsedinov/gists{/gist_id}",
      gravatar_id: "",
      html_url: "https://github.com/tshemsedinov",
      id: 4405297,
      login: "tshemsedinov",
      node_id: "MDQ6VXNlcjQ0MDUyOTc=",
      organizations_url: "https://api.github.com/users/tshemsedinov/orgs",
      received_events_url: "https://api.github.com/users/tshemsedinov/received_events",
      repos_url: "https://api.github.com/users/tshemsedinov/repos",
      score: 1,
      site_admin: false,
      starred_url: "https://api.github.com/users/tshemsedinov/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/tshemsedinov/subscriptions",
      type: "User",
      url: "https://api.github.com/users/tshemsedinov",
    },
    {
      avatar_url: "https://avatars2.githubusercontent.com/u/76031?v=4",
      events_url: "https://api.github.com/users/akella/events{/privacy}",
      followers_url: "https://api.github.com/users/akella/followers",
      following_url: "https://api.github.com/users/akella/following{/other_user}",
      gists_url: "https://api.github.com/users/akella/gists{/gist_id}",
      gravatar_id: "",
      html_url: "https://github.com/akella",
      id: 76031,
      login: "akella",
      node_id: "MDQ6VXNlcjc2MDMx",
      organizations_url: "https://api.github.com/users/akella/orgs",
      received_events_url: "https://api.github.com/users/akella/received_events",
      repos_url: "https://api.github.com/users/akella/repos",
      score: 1,
      site_admin: false,
      starred_url: "https://api.github.com/users/akella/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/akella/subscriptions",
      type: "User",
      url: "https://api.github.com/users/akella",

    }],
  userCard: {
    avatar_url: "https://avatars2.githubusercontent.com/u/4405297?v=4",
    events_url: "https://api.github.com/users/tshemsedinov/events{/privacy}",
    followers_url: "https://api.github.com/users/tshemsedinov/followers",
    following_url: "https://api.github.com/users/tshemsedinov/following{/other_user}",
    gists_url: "https://api.github.com/users/tshemsedinov/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/tshemsedinov",
    id: 4405297,
    login: "tshemsedinov",
    node_id: "MDQ6VXNlcjQ0MDUyOTc=",
    organizations_url: "https://api.github.com/users/tshemsedinov/orgs",
    received_events_url: "https://api.github.com/users/tshemsedinov/received_events",
    repos_url: "https://api.github.com/users/tshemsedinov/repos",
    score: 1,
    site_admin: false,
    starred_url: "https://api.github.com/users/tshemsedinov/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tshemsedinov/subscriptions",
    type: "User",
    url: "https://api.github.com/users/tshemsedinov",
  },
  loading: true,
  isErrorVisible: false
};
export default InitialState
